### ISSUE TITLE
Where is the info.mat?

### ISSUE THREAD

**Issue by JuZiSYJ** [aasharma90/Unprocessing_for_RAW_Denoising#5]
Hello
I am trying to download the DND dateset,However, i could not find the **info.mat** in your code, would you mind offer the info.mat,thanks :)

**Comment by aasharma90** [comment]
Hi @JuZiSYJ 

The info.mat file should be available with the DND dataset, and it might be better to use the official file so that your dataset has no compatibility issues. However, for your reference, I've provided a link below to get the info.mat file from the dataset I downloaded a while ago. 
https://www.dropbox.com/s/9cf6pn8xod8r509/info.mat?dl=0
