### ISSUE TITLE
A issue and correction method

### ISSUE THREAD

**Issue by happycaoyue** [aasharma90/Unprocessing_for_RAW_Denoising#6]
bayer_pattern = np.asarray(np.array(info[info['camera'][0][i]]['pattern']).T).tolist()

**Comment by aasharma90** [comment]
Hi @happycaoyue 

Thanks for your suggestion. Is this correction intended for solving the white balance problem reported in the README file? If yes, could you please confirm by attaching a result? Also, please do open a pull request if that's the case so that I can merge it.

If not, could you please tell what is the issue for which this correction is?

**Comment by happycaoyue** [comment]
Yes, by this way, the discoloration problem (or  the white balance problem) can be solved. The original code you write will get a wrong bayer_pattern, which is  transpose matrix of correct bayer pattern.

**Comment by aasharma90** [comment]
Hi @happycaoyue 

Thanks for your feedback. It has fixed the problem, though if you could provide any rationale (or any documentation) on why the transpose is needed that would be highly appreciated.

**Comment by aasharma90** [comment]
Hi, closing this as the issue has been resolved and there has been no further activity.
